services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "80:5000"
    env_file:
      - .env
    volumes:
      - uploads:/app/static/uploads
    networks:
      - scholaris_net

volumes:
  uploads:

networks:
  scholaris_net:
    driver: bridge
